### ISSUE TITLE
Table 'x.blocked_ips' doesn't exist

### ISSUE THREAD

**Issue by domaingood** [backdrop-contrib/ip_blocking#10]
Please uninstall module "Ban IP" then try again.DismissSQLSTATE[42S02]: Base table or view not found: 1146 Table 'tuhininf_back.tuh_se9_blocked_ips' doesn't exist: SELECT 1 FROM {blocked_ips} WHERE ip = :ip; Array ( [:ip] =>  84.81.200.16

**Comment by findlabnet** [comment]
@domaingood thanks for your interest in the module.
As far as I can see, you posted two unrelated messages here.

The first part - you are trying to install this module at the same time as "Ban IP" is installed, which must be uninstalled first.

The second error says that the database table is missing.
Please check your database and database configuration (database name and table prefixes) in settings.php.

It looks like this problem is related to moving / migration your site.

Let me know, if I can help more.

**Comment by findlabnet** [comment]
Seems like you haven't any more questions. Closed.
