### ISSUE TITLE
Do not give spammer any useful information

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ip_blocking#3]
When a spammer gets blocked he sees the following message in browsers' screen:

> Sorry, IP address HIS_IP_ADDRESS has been banned.

showing how exactly he was blocked, which could give him an idea to just change his IP and try again. I believe it's better not to give any information to malicious party, by just outputting something like:

> You have been blocked for bad behavior!

Даже сорри кажется излишним, так как нет необходимости церемониться со спаммерами.

**Comment by findlabnet** [comment]
1) Sometimes I got such message on some sites. 
I think it caused by using dynamic IP, previously banned on this site.
2) From my humble experience - 100% of spammers are robots, not real people who can see our messages.

**Update.** Ban such spambot network's members by IP may not be so good idea, because it is probably just infected windows PCs and home routers with dynamic IPs.
As result we can get huge list of banned IPs for further headaches and lost performance for our site.

> нет необходимости церемониться со спаммерами.

Может быть сочтено неполиткорректным заявлением (шутка).

**Comment by findlabnet** [comment]
@alanmels what you think about adding selector 403/404 error code to return for visitor from blocked IP? 
I did such selector in my module [Login whitelist](https://backdropcms.org/project/login_whitelist) to simplify filtering robots login attempts.

**Comment by alanmels** [comment]
Even better idea! If blocked then for surely a good reason and they should not be allowed to see anything.

**Comment by alanmels** [comment]
Just so your know the https://github.com/backdrop-contrib/protected_forms relies on this module to block spammers.

**Comment by findlabnet** [comment]
OK, I'll do it.

**Comment by findlabnet** [comment]
Done in [ver. 1.0.4](https://github.com/backdrop-contrib/ip_blocking/releases/tag/1.x-1.0.4)
Plus added option to enable logging for access attempts from blocked IPs.
